export const data = {
  alt_description: 'a crowded city street at night with neon signs',
  alternative_slugs: {
    de: 'eine-uberfullte-stadtstrasse-bei-nacht-mit-neonschildern-1eKSPSELYA4',
    en: 'a-crowded-city-street-at-night-with-neon-signs-1eKSPSELYA4',
    es: 'una-calle-de-la-ciudad-llena-de-gente-por-la-noche-con-letreros-de-neon-1eKSPSELYA4',
    fr: 'une-rue-bondee-la-nuit-avec-des-enseignes-au-neon-1eKSPSELYA4',
    it: 'una-strada-affollata-di-notte-con-insegne-al-neon-1eKSPSELYA4',
    ja: 'ネオンサインのある夜の混雑した街路-1eKSPSELYA4',
    ko: '네온사인이-있는-밤의-붐비는-도시-거리-1eKSPSELYA4',
    pt: 'uma-rua-da-cidade-lotada-a-noite-com-placas-de-neon-1eKSPSELYA4',
  },
  asset_type: 'photo',
  blur_hash: 'LFAmc7.AtRxt?d%Otn%M5PXAtoxv',
  breadcrumbs: [],
  color: '#262640',
  created_at: '2024-05-24T15:51:05Z',
  current_user_collections: [],
  description: 'a crowded city street at night with neon signs a crowded city street at night with neon signs a crowded city street at night with neon signs',
  downloads: 415,
  exif: {
    aperture: '2.8',
    exposure_time: '1/125',
    focal_length: '28.0',
    iso: 250,
    make: 'SONY',
    model: 'ILCE-7M3',
    name: 'SONY, ILCE-7M3',
  },
  height: 4000,
  id: '1eKSPSELYA4',
  liked_by_user: false,
  likes: 5000,
  links: {
    download:
      'https://unsplash.com/photos/1eKSPSELYA4/download?ixid=M3w2MTU4NTV8MHwxfGFsbHx8fHx8fHx8fDE3MTY2NTA5MDd8',
    download_location:
      'https://api.unsplash.com/photos/1eKSPSELYA4/download?ixid=M3w2MTU4NTV8MHwxfGFsbHx8fHx8fHx8fDE3MTY2NTA5MDd8',
    html: 'https://unsplash.com/photos/a-crowded-city-street-at-night-with-neon-signs-1eKSPSELYA4',
    self: 'https://api.unsplash.com/photos/a-crowded-city-street-at-night-with-neon-signs-1eKSPSELYA4',
  },
  location: {
    city: null,
    country: null,
    name: 'Tokyo Shinbashi, Japan',
    position: {latitude: 0, longitude: 0},
  },
  meta: {index: true},
  promoted_at: '2024-05-25T09:06:00Z',
  public_domain: false,
  related_collections: {
    results: [[Object], [Object], [Object]],
    total: 3,
    type: 'related',
  },
  slug: 'a-crowded-city-street-at-night-with-neon-signs-1eKSPSELYA4',
  sponsorship: null,
  tags: [
    {title: 'japan', type: 'search'},
    {title: 'tokyo shinbashi', type: 'search'},
    {title: "drinker's paradise", type: 'search'},
    {title: 'neon sign', type: 'search'},
    {title: 'night view', type: 'search'},
    {title: 'tokyo', type: 'search'},
    {title: 'drinking area', type: 'search'},
    {title: 'urban', type: 'search'},
    {title: 'night life', type: 'search'},
    {title: 'bag', type: 'search'},
    {title: 'handbag', type: 'search'},
    {title: 'human', type: 'search'},
    {title: 'man', type: 'search'},
    {title: 'male', type: 'search'},
    {title: 'adult', type: 'search'},
    {title: 'shoe', type: 'search'},
    {title: 'lamp', type: 'search'},
    {title: 'town', type: 'search'},
  ],
  tags_preview: [
    {title: 'japan', type: 'search'},
    {title: 'tokyo shinbashi', type: 'search'},
    {title: "drinker's paradise", type: 'search'},
  ],
  topic_submissions: {},
  topics: [],
  updated_at: '2024-05-25T11:23:12Z',
  urls: {
    full: 'https://images.unsplash.com/photo-1716565679311-5179cc3dd908?crop=entropy&cs=srgb&fm=jpg&ixid=M3w2MTU4NTV8MHwxfGFsbHx8fHx8fHx8fDE3MTY2NTA5MDd8&ixlib=rb-4.0.3&q=85',
    raw: 'https://images.unsplash.com/photo-1716565679311-5179cc3dd908?ixid=M3w2MTU4NTV8MHwxfGFsbHx8fHx8fHx8fDE3MTY2NTA5MDd8&ixlib=rb-4.0.3',
    regular:
      'https://images.unsplash.com/photo-1716565679311-5179cc3dd908?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTU4NTV8MHwxfGFsbHx8fHx8fHx8fDE3MTY2NTA5MDd8&ixlib=rb-4.0.3&q=80&w=1080',
    small:
      'https://images.unsplash.com/photo-1716565679311-5179cc3dd908?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTU4NTV8MHwxfGFsbHx8fHx8fHx8fDE3MTY2NTA5MDd8&ixlib=rb-4.0.3&q=80&w=400',
    small_s3:
      'https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1716565679311-5179cc3dd908',
    thumb:
      'https://images.unsplash.com/photo-1716565679311-5179cc3dd908?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MTU4NTV8MHwxfGFsbHx8fHx8fHx8fDE3MTY2NTA5MDd8&ixlib=rb-4.0.3&q=80&w=200',
  },
  user: {
    accepted_tos: true,
    bio: "Maybe I'm like the insects that flock to the light at night.",
    first_name: 'mos',
    for_hire: true,
    id: 'YSTZkkK3V1o',
    instagram_username: null,
    last_name: 'design',
    links: {
      followers: 'https://api.unsplash.com/users/mosdesign/followers',
      following: 'https://api.unsplash.com/users/mosdesign/following',
      html: 'https://unsplash.com/@mosdesign',
      likes: 'https://api.unsplash.com/users/mosdesign/likes',
      photos: 'https://api.unsplash.com/users/mosdesign/photos',
      portfolio: 'https://api.unsplash.com/users/mosdesign/portfolio',
      self: 'https://api.unsplash.com/users/mosdesign',
    },
    location: 'tokyo japan',
    name: 'mos design',
    portfolio_url: 'https://mos.chu.jp',
    profile_image: {
      large:
        'https://images.unsplash.com/profile-1664189090215-f1cd1a693fbbimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128',
      medium:
        'https://images.unsplash.com/profile-1664189090215-f1cd1a693fbbimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64',
      small:
        'https://images.unsplash.com/profile-1664189090215-f1cd1a693fbbimage?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32',
    },
    social: {
      instagram_username: null,
      paypal_email: null,
      portfolio_url: 'https://mos.chu.jp',
      twitter_username: null,
    },
    total_collections: 0,
    total_illustrations: 0,
    total_likes: 271,
    total_photos: 768,
    total_promoted_illustrations: 0,
    total_promoted_photos: 136,
    twitter_username: null,
    updated_at: '2024-05-25T15:20:56Z',
    username: 'mosdesign',
  },
  views: 55268,
  width: 6000,
};
